parameters:
    lia.factory.dhtmlx.grid.class: Lia\Bridge\DhtmlxBundle\Grid\FactoryService


services:
    lia.factory.dhtmlx.grid:
        class: %lia.factory.dhtmlx.grid.class%
        calls:
            - ['setContainer', [@service_container]]